fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [pep8-naming, flake8-docstrings]
        args: [--max-line-length=88]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with cargo fmt.
        entry: cargo fmt
        language: system
        types: [rust]
        args: ["--"]
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: system
        types: [file]
        files: ^.*(Cargo\.toml|Cargo\.lock|.*\.rs)$
        pass_filenames: false
