#!/usr/bin/env python3
# Copyright (C) 2026 J. Nathanael Philipp (jnphilipp) <jnathanael@philipp.land>
#
# Bikkuri, calculate the surprisal of words in texts.
#
# This file is part of bikkuri.
#
# bikkuri is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bikkuri is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bikkuri. If not, see <http://www.gnu.org/licenses/>
"""Tests for bikkuri."""

import unittest

from bikkuri import NGramSurprisal, UniGramSurprisal


class NGramSurprisalTests(unittest.TestCase):
    """TopicContextModel tests."""

    def setUp(self) -> None:
        """Set up."""
        self.texts = [
            [
                "lorem",
                "ipsum",
                "dolor",
                "sit",
                "amet",
                "consectetur",
                "adipiscing",
                "elit",
                "sed",
                "do",
                "eiusmod",
                "tempor",
                "incididunt",
                "ut",
                "labore",
                "et",
                "dolore",
                "magna",
                "aliqua",
                "lectus",
                "vitae",
                "mi",
                "mauris",
                "facilisis",
                "luctus",
                "posuere",
                "elementum",
                "cursus",
                "fermentum",
                "non",
                "massa",
                "litora",
                "ultricies",
                "donec",
                "consectetur",
                "lectus",
                "sodales",
                "elementum",
                "facilisis",
                "fermentum",
                "senectus",
                "et",
                "mi",
                "lobortis",
                "iaculis",
                "fermentum",
                "ante",
                "consequat",
                "aptent",
                "quam",
                "ultricies",
                "sed",
                "libero",
            ],
            [
                "convallis",
                "fringilla",
                "dignissim",
                "massa",
                "arcu",
                "posuere",
                "in",
                "imperdiet",
                "eu",
                "at",
                "aenean",
                "sit",
                "sollicitudin",
                "arcu",
                "consectetur",
                "bibendum",
                "a",
                "class",
                "consequat",
                "nulla",
                "fusce",
                "donec",
                "fringilla",
                "lobortis",
                "vehicula",
                "tristique",
                "hac",
                "vestibulum",
                "aenean",
                "fusce",
                "hac",
                "eros",
                "pulvinar",
                "cubilia",
                "ultricies",
                "bibendum",
                "tempor",
                "at",
                "gravida",
                "malesuada",
            ],
            [
                "quam",
                "nullam",
                "eget",
                "est",
                "ac",
                "fusce",
                "elit",
                "eros",
                "tellus",
                "facilisis",
                "malesuada",
                "hendrerit",
                "lectus",
                "dictumst",
                "praesent",
                "sodales",
                "augue",
                "netus",
                "nullam",
                "eget",
                "justo",
                "duis",
                "nulla",
                "eros",
                "potenti",
                "at",
            ],
            [
                "sagittis",
                "non",
                "nullam",
                "maximus",
                "purus",
                "nisi",
                "ante",
                "sollicitudin",
                "etiam",
                "urna",
                "volutpat",
                "mauris",
                "semper",
                "sollicitudin",
                "felis",
                "aliquet",
                "nullam",
                "praesent",
                "vel",
                "curabitur",
                "habitasse",
                "condimentum",
                "metus",
                "eu",
                "pretium",
                "maximus",
                "tristique",
                "litora",
                "nisl",
                "quam",
                "purus",
                "facilisis",
                "laoreet",
                "dignissim",
            ],
            [
                "dui",
                "proin",
                "adipiscing",
                "consequat",
                "felis",
                "amet",
                "laoreet",
                "blandit",
                "laoreet",
                "porttitor",
                "litora",
                "in",
                "orci",
                "quis",
                "himenaeos",
                "nam",
                "adipiscing",
                "nisi",
                "metus",
                "pulvinar",
                "ante",
                "dignissim",
                "dolor",
                "dapibus",
                "a",
                "vivamus",
                "nisi",
            ],
            [
                "sit",
                "dapibus",
                "neque",
                "sapien",
                "cubilia",
                "porttitor",
                "egestas",
                "proin",
                "nunc",
                "purus",
                "nisi",
                "dapibus",
                "nunc",
                "venenatis",
                "cras",
                "mauris",
                "suscipit",
                "pellentesque",
                "netus",
                "porta",
                "vitae",
                "fermentum",
                "turpis",
                "arcu",
                "odio",
                "duis",
                "erat",
                "proin",
                "tellus",
                "lectus",
                "etiam",
                "vitae",
                "pulvinar",
                "magna",
                "turpis",
                "velit",
                "curabitur",
                "mauris",
                "suscipit",
                "turpis",
                "congue",
                "dui",
                "suscipit",
                "neque",
                "quam",
                "amet",
                "vestibulum",
                "quam",
                "class",
                "suspendisse",
                "torquent",
                "risus",
                "nisi",
                "laoreet",
                "tellus",
                "lectus",
                "interdum",
                "habitant",
                "molestie",
                "commodo",
                "tristique",
                "scelerisque",
            ],
            [
                "malesuada",
                "curabitur",
                "erat",
                "mauris",
                "tempor",
                "vel",
                "leo",
                "condimentum",
                "class",
                "pharetra",
                "platea",
                "justo",
                "rutrum",
                "egestas",
                "magna",
                "interdum",
                "per",
                "dolor",
                "aliquet",
                "vitae",
                "hac",
                "eleifend",
                "torquent",
                "maximus",
                "felis",
                "nullam",
                "ante",
                "elit",
                "etiam",
                "nisl",
                "mattis",
                "consectetur",
                "ipsum",
                "nisl",
                "semper",
                "accumsan",
            ],
            [
                "diam",
                "pulvinar",
                "conubia",
                "purus",
                "libero",
                "consequat",
                "turpis",
                "vulputate",
                "hac",
                "donec",
                "porttitor",
                "eleifend",
                "rhoncus",
                "volutpat",
                "leo",
                "sapien",
                "condimentum",
                "conubia",
                "rhoncus",
                "torquent",
                "commodo",
                "non",
            ],
            [
                "morbi",
                "etiam",
                "porta",
                "ornare",
                "posuere",
                "integer",
                "etiam",
                "purus",
                "pulvinar",
                "nullam",
                "justo",
                "amet",
                "arcu",
                "dictum",
                "vitae",
                "quisque",
                "etiam",
            ],
            [
                "feugiat",
                "massa",
                "maximus",
                "ultrices",
                "ipsum",
                "nec",
                "dui",
                "enim",
                "orci",
                "convallis",
                "est",
                "rhoncus",
                "nisi",
                "congue",
                "felis",
                "nisi",
                "euismod",
            ],
        ]

    def test_unigram_surprisal(self) -> None:
        """Test unigram surprisal."""
        unigram_surprisal = NGramSurprisal(1)
        unigram_surprisal.fit(self.texts)
        self.assertEqual(
            [
                [
                    ("lorem", 8.383704292474052),
                    ("ipsum", 6.798741791752896),
                    ("dolor", 6.798741791752896),
                    ("sit", 6.798741791752896),
                    ("amet", 6.383704292474052),
                    ("consectetur", 6.383704292474052),
                    ("adipiscing", 6.798741791752896),
                ],
                [
                    ("feugiat", 8.383704292474052),
                    ("massa", 6.798741791752896),
                    ("maximus", 6.383704292474052),
                    ("ultrices", 8.383704292474052),
                    ("ipsum", 6.798741791752896),
                    ("nec", 8.383704292474052),
                ],
            ],
            unigram_surprisal(
                [
                    [
                        "lorem",
                        "ipsum",
                        "dolor",
                        "sit",
                        "amet",
                        "consectetur",
                        "adipiscing",
                    ],
                    [
                        "feugiat",
                        "massa",
                        "maximus",
                        "ultrices",
                        "ipsum",
                        "nec",
                    ],
                ]
            ),
        )

        unigram_surprisal = UniGramSurprisal()
        unigram_surprisal.fit(self.texts)
        self.assertEqual(
            [
                [
                    ("lorem", 8.383704292474052),
                    ("ipsum", 6.798741791752896),
                    ("dolor", 6.798741791752896),
                    ("sit", 6.798741791752896),
                    ("amet", 6.383704292474052),
                    ("consectetur", 6.383704292474052),
                    ("adipiscing", 6.798741791752896),
                ],
                [
                    ("feugiat", 8.383704292474052),
                    ("massa", 6.798741791752896),
                    ("maximus", 6.383704292474052),
                    ("ultrices", 8.383704292474052),
                    ("ipsum", 6.798741791752896),
                    ("nec", 8.383704292474052),
                ],
            ],
            unigram_surprisal(
                [
                    [
                        "lorem",
                        "ipsum",
                        "dolor",
                        "sit",
                        "amet",
                        "consectetur",
                        "adipiscing",
                    ],
                    [
                        "feugiat",
                        "massa",
                        "maximus",
                        "ultrices",
                        "ipsum",
                        "nec",
                    ],
                ]
            ),
        )

    def test_bigram_surprisal(self) -> None:
        """Test bigram surprisal."""
        bigram_surprisal = NGramSurprisal(2)
        bigram_surprisal.fit(self.texts)
        self.assertEqual(
            [
                [
                    ("lorem", 3.321928094887362),
                    ("ipsum", 0.0),
                    ("dolor", 1.5849625007211563),
                    ("sit", 1.5849625007211563),
                    ("amet", 1.5849625007211563),
                    ("consectetur", 2.0),
                    ("adipiscing", 2.0),
                ],
                [
                    ("feugiat", 3.321928094887362),
                    ("massa", 0.0),
                    ("maximus", 1.5849625007211563),
                    ("ultrices", 2.0),
                    ("ipsum", 0.0),
                    ("nec", 1.5849625007211563),
                ],
            ],
            bigram_surprisal(
                [
                    [
                        "lorem",
                        "ipsum",
                        "dolor",
                        "sit",
                        "amet",
                        "consectetur",
                        "adipiscing",
                    ],
                    [
                        "feugiat",
                        "massa",
                        "maximus",
                        "ultrices",
                        "ipsum",
                        "nec",
                    ],
                ]
            ),
        )


if __name__ == "__main__":
    unittest.main()
